using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Optimum.ERP.Models.Constants
{
    public class ReportColorEnum
    {
        public static Color LabelColor
        {
            get
            { return Color.LightBlue; }
        }
        public static Color FieldColor
        {
            get { return Color.LightYellow; }
        }
        public static Color LineColor
        {
            get { return Color.Black; }
        }
        public static Color ForeColor
        {
            get
            { return Color.Black; }
        }
        public enum LineOrientation
        {
            Horizontal,
            Vertical
        }
        public enum ControlType
        {
            FIELD = 0,
            LABEL = 1,
            LINE = 2,
            LOGO = 3
        }
        public partial class PrintFormatFieldConst
        {
            public const string CompanyMas = $@"CName as COMPANY_NAME,Cadd1 as COMPANY_ADDRESS1,
                Cadd2 as COMPANY_ADDRESS2,Cadd3 as COMPANY_ADDRESS3,
                Cphone as COMPANY_PHONE,CEmail as COMPANY_EMAIL,CGSTIN as COMPANY_GSTIN,CStateName as COMPANY_STATENAME,PINCODE as COMPANY_PINCODE";

            public const string AccMas = $@"Accmas.AccPrintName as Party_PrintName, Accmas.accname as PARTY_NAME, Accmas.address1 as PARTY_ADDRESS1,Accmas.address2  as PARTY_ADDRESS2,Accmas.address3  as PARTY_ADDRESS3, 
                Accmas.PIN as PARTY_PIN, Accmas.Phone as PARTY_PHONE,Accmas.email as PARTY_EMAIL,Accmas.VendCode As VENDORCODE,Accmas.GSTIN as Party_GSTNO, Accmas.Panno as PARTY_PANNO, 
                Accmas.creditdays as Party_CreditDays, Accmas.ItField1 as Acc_OF_1, Accmas.ItField2 as Acc_OF_2, Accmas.ItField3 as Acc_OF_3, Accmas.ItField4 as Acc_OF_4, Accmas.ItField5 as Acc_OF_5, 
                Accmas.ItField6 as Acc_OF_6, Accmas.ItField7 as Acc_OF_7, Accmas.ItField8 as Acc_OF_8, Accmas.ItField9 as Acc_OF_9, Accmas.ItField10 as Acc_OF_10";


            public const string AccMas2 = $@"Accmas2.AccPrintName as PARTY2_PrintName, Accmas2.accname as PARTY2_NAME, Accmas2.address1 as PARTY2_ADDRESS1,Accmas2.address2  as PARTY2_ADDRESS2,Accmas2.address3  as PARTY2_ADDRESS3, 
            Accmas2.PIN as PARTY2_PIN, Accmas2.Phone as PARTY2_PHONE,Accmas2.email as PARTY2_EMAIL,Accmas2.VendCode As PARTY2_VENDORCODE,Accmas2.GSTIN as PARTY2_GSTNO, Accmas2.Panno as PARTY2_PANNO, 
            Accmas2.creditdays as PARTY2_CreditDays";

            public const string AccMas3 = $@"Accmas3.AccPrintName as PARTY3_PrintName, Accmas3.accname as PARTY3_NAME, Accmas3.address1 as PARTY3_ADDRESS1,Accmas3.address2  as PARTY3_ADDRESS2,Accmas3.address3  as PARTY3_ADDRESS3, 
				Accmas3.PIN as PARTY3_PIN, Accmas3.Phone as PARTY3_PHONE,Accmas3.email as PARTY3_EMAIL,Accmas3.VendCode As PARTY3_VENDORCODE,Accmas3.GSTIN as PARTY3_GSTNO, Accmas3.Panno as PARTY3_PANNO, 
				Accmas3.creditdays as PARTY3_CreditDays";

            public const string ConsigneeMas = $@"Accmas.AccPrintName as Party_PrintName, Accmas.accname as PARTY_NAME, Accmas.address1 as PARTY_ADDRESS1,Accmas.address2  as PARTY_ADDRESS2,Accmas.address3  as PARTY_ADDRESS3, 
                Accmas.PIN as PARTY_PIN, Accmas.Phone as PARTY_PHONE,Accmas.email as PARTY_EMAIL,Accmas.VendCode As VENDORCODE,Accmas.GSTIN as Party_GSTNO, Accmas.Panno as PARTY_PANNO";

            public const string RawMas = $@"RawMas.RawCodenew as ITEM_CODE, RawMas.Rawdesc as ITEM_NAME,RawMas.Rawname as ITEM_DESCRIPTION, 
                Rawmas.rate AS ITEM_RATE, 
                Rawmas.Mrp as ITEM_MRP, 
                Rawmas.itField1 as ITEM_OPTIONAL_FIELD1, Rawmas.itField2 as ITEM_OPTIONAL_FIELD2,Rawmas.itField3 as ITEM_OPTIONAL_FIELD3, 
                Rawmas.itField4 as ITEM_OPTIONAL_FIELD4,Rawmas.itField5 as ITEM_OPTIONAL_FIELD5,Rawmas.itField6 as ITEM_OPTIONAL_FIELD6,
                Rawmas.itField7 as ITEM_OPTIONAL_FIELD7,Rawmas.itField8 as ITEM_OPTIONAL_FIELD8,Rawmas.itField9 as ITEM_OPTIONAL_FIELD9,
                Rawmas.itField10 as ITEM_OPTIONAL_FIELD10";

            public const string UnitMas = "UnitMas.UnitName as ITEM_UNIT,UnitMas.UnitShortName as ITEM_SHORTUNIT";

            public const string HSNMas = "HSNName as HSN_CODE, HSNDesc as HSN_DESCRIPTION, HSNMas.UQC As HSN_UQC, HSNMas.GST as HSN_GST";

            public const string StateMas = "StateName as STATE_NAME, StateCodeNew as STATE_CODE";
            public const string StateMas2 = "StateMas2.StateName as STATE2_NAME, StateMas2.StateCodeNew as STATE2_CODE";

            public const string SeriesMas = $@"SeriesMas.SeriesName, SeriesMas.SeriesPrintName";

            public const string SaleMas = $@"SaleMas.DocNo as INVOICE_NO,
                SaleMas.SaleDate as INVOICE_DATE,
                SaleMas.TaxableAmt as INVOICE_TaxableAmt,
                saleMas.TotalAmt as INVOICE_TotalAmt,
                saleMas.BillAmt as INVOICE_BillAmt,
                Case When Region = 0 then SaleMas.GST1 When Region = 1 then 0 End MAS_CGST_Perc, 
                Case When Region = 0 then SaleMas.GST2 When Region = 1 then 0 End MAS_SGST_Perc, 
                Case When Region = 0 then SaleMas.GST1Amt When Region = 1 then 0 End MAS_CGST_AMT, 
                Case When Region = 0 then SaleMas.GST2Amt WHEN Region = 1 then 0 End MAS_SGST_AMT, 
                Case When Region = 1 then SaleMas.GST1 When Region = 0 then 0 End MAS_IGST_Perc, 
                Case When Region = 1 then SaleMas.GST1Amt When Region = 0 then 0 End MAS_IGST_AMT,
                Salemas.COther1, Salemas.COther2, Salemas.COther3, Salemas.COther4, Salemas.COther5, 
                Salemas.OtherAmt1,Salemas.OtherAmt2,Salemas.OtherAmt3,Salemas.OtherAmt4,Salemas.OtherAmt5,
                Salemas.Perc1,Salemas.Perc2,Salemas.Perc3,Salemas.Perc4,Salemas.Perc5,
				SaleMas.chno As ChallanNo, 
				SaleMas.chdate As ChallanDate, 
                Salemas.Narr1 as Narration1,
				Salemas.Narr2 as Narration2,
				Salemas.Narr3 as Narration3,
				Salemas.Narr4 as Narration4,
				Salemas.Narr5 as Narration5,
				Salemas.Narr6 as Narration6,
				Salemas.Narr7 as Narration7,
				Salemas.Narr8 as Narration8,
				Salemas.Narr9 as Narration9,
				Salemas.Narr10 as Narration10,
                IRN, AckNo,AckDate,CancelIRN, CancelIRNDate, EWayBillCancelDate,ewayBillNo,ewayBillDate,EwbValidTill as EwayBillValidTill";
            // Region 0 = Local and 1 = Central
            public const string SaleDet = $@"SaleDet.SrNo as DETAIL_SrNo, SaleDet.Pack as DETAIL_Pack, SaleDet.PerPackQty as DETAIL_PerPackQty, SaleDet.qty as DETAIL_QTY,
                SaleDet.SaleRate as DETAIL_SaleRate, SaleDet.Amount as DETAIL_Amount, SaleDet.Disc as DETAIL_DiscPERC, SaleDet.DiscAmt as DETAIL_DiscAMT, 
                (SaleDet.Amount-SaleDet.DiscAmt) as DETAIL_TaxableAmt,(SaleDet.Amount-SaleDet.DiscAmt+SaleDet.GST1Amt+SaleDet.GST2Amt) as DETAIL_ITEM_AMT,
                Case When Region = 0 then SaleDet.GST1 When Region = 1 then 0 End DETAIL_CGSTPerc, 
                Case When Region = 0 then SaleDet.GST2 When Region = 1 then 0 End DETAIL_SGSTPerc, 
                Case When Region = 0 then SaleDet.GST1Amt When Region = 1 then 0 End as DETAIL_CGSTAmt, 
                Case When Region = 0 then SaleDet.GST2Amt When Region = 1 then 0 End as DETAIL_SGSTAmt,
                Case When Region = 1 then SaleDet.GST1 When Region = 0 then 0 End DETAIL_IGST_Perc, 
                Case When Region = 1 then SaleDet.GST1Amt When Region = 0 then 0 End DETAIL_IGST_AMT,
                SaleDet.Opfield1 as DETAIL_Optional1,
				SaleDet.Opfield2 as DETAIL_Optional2,
				SaleDet.Opfield3 as DETAIL_Optional3,
				SaleDet.Opfield4 as DETAIL_Optional4,
				SaleDet.Opfield5 as DETAIL_Optional5,
				SaleDet.Opfield6 as DETAIL_Optional6,
				SaleDet.Opfield7 as DETAIL_Optional7,
				SaleDet.Opfield8 as DETAIL_Optional8,
				SaleDet.Opfield9 as DETAIL_Optional9,
				SaleDet.Opfield10 as DETAIL_Optional10";

            public const string PIMas = $@"PIMas.DocNo as PI_NO,
                PIMas.PIDate as PI_DATE,
                PIMas.TaxableAmt as PI_TaxableAmt,
                PIMas.TotalAmt as PI_Amount,
                PIMas.PINarration as PI_Remark,
                Case When Region = 0 then PIMas.GST1 When Region = 1 then 0 End MAS_CGST_Perc, 
                Case When Region = 0 then PIMas.GST2 When Region = 1 then 0 End MAS_SGST_Perc, 
                Case When Region = 0 then PIMas.GST1Amt When Region = 1 then 0 End MAS_CGST_AMT, 
                Case When Region = 0 then PIMas.GST2Amt WHEN Region = 1 then 0 End MAS_SGST_AMT, 
                Case When Region = 1 then PIMas.GST1 When Region = 0 then 0 End MAS_IGST_Perc, 
                Case When Region = 1 then PIMas.GST1Amt When Region = 0 then 0 End MAS_IGST_AMT,
                PIMas.COther1, PIMas.COther2, PIMas.COther3, PIMas.COther4, PIMas.COther5, 
                PIMas.OtherAmt1,PIMas.OtherAmt2,PIMas.OtherAmt3,PIMas.OtherAmt4,PIMas.OtherAmt5,
                PIMas.Perc1,PIMas.Perc2,PIMas.Perc3,PIMas.Perc4,PIMas.Perc5,
				PIMas.chno As ChallanNo, 
				PIMas.chdate As ChallanDate, 
                PIMas.Narr1 as Narration1,
				PIMas.Narr2 as Narration2,
				PIMas.Narr3 as Narration3,
				PIMas.Narr4 as Narration4,
				PIMas.Narr5 as Narration5,
				PIMas.Narr6 as Narration6,
				PIMas.Narr7 as Narration7,
				PIMas.Narr8 as Narration8,
				PIMas.Narr9 as Narration9,
				PIMas.Narr10 as Narration10
";
            // Region 0 = Local and 1 = Central
            public const string PIDet = $@"PIDet.SrNo as DETAIL_SrNo, PIDet.Pack as DETAIL_Pack, PIDet.PerPackQty as DETAIL_PerPackQty, PIDet.qty as DETAIL_QTY,
                PIDet.PIRate as DETAIL_PIRate, PIDet.Amount as DETAIL_Amount, PIDet.Disc as DETAIL_DiscPERC, PIDet.DiscAmt as DETAIL_DiscAMT, 
                (PIDet.Amount-PIDet.DiscAmt) as DETAIL_TaxableAmt,(PIDet.Amount-PIDet.DiscAmt+PIDet.GST1Amt+PIDet.GST2Amt) as DETAIL_ITEM_AMT,
                Case When Region = 0 then PIDet.GST1 When Region = 1 then 0 End DETAIL_CGSTPerc, 
                Case When Region = 0 then PIDet.GST2 When Region = 1 then 0 End DETAIL_SGSTPerc, 
                Case When Region = 0 then PIDet.GST1Amt When Region = 1 then 0 End as DETAIL_CGSTAmt, 
                Case When Region = 0 then PIDet.GST2Amt When Region = 1 then 0 End as DETAIL_SGSTAmt,
                Case When Region = 1 then PIDet.GST1 When Region = 0 then 0 End DETAIL_IGST_Perc, 
                Case When Region = 1 then PIDet.GST1Amt When Region = 0 then 0 End DETAIL_IGST_AMT,
                PIDet.Opfield1 as DETAIL_Optional1,
				PIDet.Opfield2 as DETAIL_Optional2,
				PIDet.Opfield3 as DETAIL_Optional3,
				PIDet.Opfield4 as DETAIL_Optional4,
				PIDet.Opfield5 as DETAIL_Optional5,
				PIDet.Opfield6 as DETAIL_Optional6,
				PIDet.Opfield7 as DETAIL_Optional7,
				PIDet.Opfield8 as DETAIL_Optional8,
				PIDet.Opfield9 as DETAIL_Optional9,
				PIDet.Opfield10 as DETAIL_Optional10,
				PIDet.Height,
				PIDet.Width,
				PIDet.NOS";

            public const string ChallanMas = $@" ChallanMas.DocNo as CHALLAN_No, ChallanMas.ChallanDate as Challan_Date, Transport, Carrier,
                ChallanMas.GST1 as GSTPerc1, ChallanMas.GST2 as GSTPerc2, Challanmas.TaxableAmt, ChallanMas.GST1Amt, ChallanMas.GST2Amt,
	            ChallanMas.OtherAmt1, ChallanMas.OtherAmt2, ChallanMas.OtherAmt3, ChallanMas.OtherAmt4, ChallanMas.OtherAmt5, ChallanMas.OtherAmt6,	
	            ChallanMas.ChallanAmt, 
	            Challanmas.Narr1 as Narration1,Challanmas.Narr2 as Narration2,Challanmas.Narr3 as Narration3,Challanmas.Narr4 as Narration4,Challanmas.Narr5 as Narration5,
	            Challanmas.Narr6 as Narration6, Challanmas.Narr7 as Narration7, Challanmas.Narr8 as Narration8, Challanmas.Narr9 as Narration9, 
                Challanmas.Narr10 as Narration10";

            public const string ChallanDet = $@" ChallanDet.SrNo as DETAIL_SRNO, ChallanDet.Pack as DETAIL_PACK, ChallanDet.PerPackQty as DETAIL_PERPACKQTY,
                ChallanDet.qty As DETAIL_QTY, ChallanDet.Rate As DETAIL_Rate,
	            ChallanDet.GST1 as Detail_GSTPerc1, ChallanDet.GST2 as Detail_GSTPerc2, ChallanDet.GST1AMT as Detail_GSTAmt1, ChallanDet.GST2Amt as Detail_GSTAmt2, 
	            ChallanDet.Amount as Detail_Amount,	
                ChallanDet.Opfield1 as DETAIL_Optional1, ChallanDet.Opfield2 as DETAIL_Optional2, ChallanDet.Opfield3 as DETAIL_Optional3,
	            ChallanDet.Opfield4 as DETAIL_Optional4, ChallanDet.Opfield5 as DETAIL_Optional5, ChallanDet.Opfield6 as DETAIL_Optional6, 
                ChallanDet.Opfield7 as DETAIL_Optional7, ChallanDet.Opfield8 as DETAIL_Optional8, ChallanDet.Opfield9 as DETAIL_Optional9, 
                ChallanDet.Opfield10 as DETAIL_Optional10";

            public const string BillMas = $@"DocNo AS Bill_No,	BillMas.BillDate AS Bill_Date,BillMas.BillTime, BillMas.DailyDocNo, '' as BillTypeName,
	            BillMas.OtherLbl1,BillMas.OtherLbl2,BillMas.OtherLbl3,BillMas.OtherLbl4,BillMas.OtherLbl5,BillMas.Remarks,
	            BillMas.Total as TOTAL_AMOUNT, 
	            BillMas.OtherPerc1,	BillMas.OtherPerc2,	BillMas.OtherPerc3,	BillMas.OtherPerc4,	BillMas.OtherPerc5,
	            BillMas.OtherAmt1, 	BillMas.OtherAmt2, BillMas.OtherAmt3, BillMas.OtherAmt4,BillMas.OtherAmt5,BillMas.BillAmt as Bill_Amount,
                BillMas.CustomerName as Customer_Name, billmas.CustAddress1 as Customer_Address1, Billmas.HDCustAddress2 as Customer_Address2, 
                billmas.CustMobile as Customer_Mobile, billmas.HDCustMobile2 as Customer_Mobile2";

            public const string BillDet = $@"
                BillDet.qty as DETAIL_QTY,
	            BillDet.Rate as DETAIL_Rate, 
	            BillDet.MRP as DETAIL_MRP, 
	            BillDet.Amount as DETAIL_AMOUNT, 
	            BillDet.DiscPerc as DETAIL_DiscPerc, 
	            BillDet.DiscAmount as DETAIL_DiscAmount,
	            BillDet.GSTPerc AS Detail_GSTPerc,
                CAST(ROW_NUMBER() OVER (ORDER BY Rawname ) AS INT) AS DETAIL_SrNo,
	            Case When BillDet.IsTaxExtra = 0 then 'Tax Inclusive' When BillDet.IsTaxExtra = 1 then 'Tax Extra' end as Detail_TaxType,
	            Case When BillDet.IsTaxExtra = 0 then (BillDet.Rate * 100) / (100 + BillDet.GSTPerc) When BillDet.IsTaxExtra = 1 then BillDet.Rate end as Detail_Taxable_Rate,
	            Case When BillDet.IsTaxExtra = 0 then (BillDet.Rate * 100) / (100 + BillDet.GSTPerc) * BillDet.Qty When BillDet.IsTaxExtra = 1 then BillDet.Rate * BillDet.Qty end as Detail_Taxable_Amount,
	            SUM(BillDet.qty) OVER() AS QTY, BillDet.Amount
	        ";

            public const string ReceiptMas = "Inde";
            public const string ReceiptDet = "4";

            public const string RGPMas = $@"RGPMas.DocNo as RGP_NO, RGPMas.RGPDate as RGP_DATE,
                RGPMas.TotalAmt as RGP_Amt,
                RGPmas.Narr1 as Narration1,
				RGPmas.Narr2 as Narration2,
				RGPmas.Narr3 as Narration3,
				RGPmas.Narr4 as Narration4,
				RGPmas.Narr5 as Narration5,
				RGPmas.Narr6 as Narration6,
				RGPmas.Narr7 as Narration7,
				RGPmas.Narr8 as Narration8,
				RGPmas.Narr9 as Narration9,
				RGPmas.Narr10 as Narration10,
				RGPmas.Distance,
				RGPmas.TransDocNo,
				RGPmas.TransId,
				RGPmas.TransName,
				RGPmas.TransDocDate,
				RGPmas.VehicleNo,
				Case when RGPmas.TransMode = 1 then 'By Road' when 
				RGPmas.TransMode = 2 then 'By Train' When 
				RGPmas.TransMode = 3 then 'By Air' When 
				RGPmas.TransMode = 4 then 'by Ship' End as TransportMode,
				RGPmas.TotalQty,
				RGPmas.TaxableAmt as TaxableAmount,
				RGPmas.TaxPerc1,
				RGPmas.TaxPerc2,
				RGPmas.GstAmt1,
				RGPmas.GstAmt2,
				RGPmas.OtherAmt,
				RGPmas.TotalAmt,
				RGPmas.ewayBillNo,
				RGPmas.ewayBillDate,
				RGPmas.LocationCode,
				RGPmas.EwbValidTill,
                StateMas3.StateName as StateName3,
				CASE WHEN RGPMas.TransType=1 THEN 'REGULAR'
				WHEN RGPMas.TransType=2 THEN 'BILL TO SHIP TO'
				WHEN RGPMas.TransType=3 THEN 'BILL FROM-DISPATCH FROM'
				WHEN RGPMas.TransType=4 THEN '--' END AS Ewb_TransType,
				JobWorkProcessMas.JobWorkProcessName as PurposName,
				dbo.NumberToWords(RGPmas.TotalAmt) AS AmountInWords";


            public const string RGPDet = $@"RGPDet.SrNo as DETAIL_SrNo, RGPDet.qty as DETAIL_QTY,
                RGPDet.Rate as DETAIL_RGPRate, RGPDet.Amount as DETAIL_Amount, 
                RGPDet.Opfield1 as DETAIL_Optional1,
				RGPDet.Opfield2 as DETAIL_Optional2,
				RGPDet.Opfield3 as DETAIL_Optional3,
				RGPDet.Opfield4 as DETAIL_Optional4,
				RGPDet.Opfield5 as DETAIL_Optional5,
				RGPDet.Opfield6 as DETAIL_Optional6,
				RGPDet.Opfield7 as DETAIL_Optional7,
				RGPDet.Opfield8 as DETAIL_Optional8,
				RGPDet.Opfield9 as DETAIL_Optional9,
				RGPDet.Opfield10 as DETAIL_Optional10,
				RGPDet.TaxableAmount as DETAIL_TaxableAmount,
				RGPDet.GST1 as DETAIL_GST1,
				RGPDet.GST2 as DETAIL_GST2,
				RGPDet.GST1Amt as DETAIL_GST1Amt,
				RGPDet.GST2Amt as DETAIL_GST2Amt,
				RGPDet.TotalAmount as DETAIL_TotalAmount,
				RGPDet.GST1+RGPDet.GST2 as DETAIL_TOT_GST,
				RGPDet.GST1Amt+RGPDet.GST2Amt as DETAIL_TOT_GSTAmt";
            public const string RRGPMas = $@"RRGPMas.RRGPCode as RRGP_NO, RRGPMas.RRGPDate as RRGP_DATE,
                RRGPMas.TotalAmt as RRGP_Amt,
                RRGPMas.Narr1 as Narration1,
				RRGPMas.Narr2 as Narration2,
				RRGPMas.Narr3 as Narration3,
				RRGPMas.Narr4 as Narration4,
				RRGPMas.Narr5 as Narration5,
				RRGPMas.Narr6 as Narration6,
				RRGPMas.Narr7 as Narration7,
				RRGPMas.Narr8 as Narration8,
				RRGPMas.Narr9 as Narration9,
				RRGPMas.Narr10 as Narration10,
				RRGPMas.Distance,
				RRGPMas.TransDocNo,
				RRGPMas.TransId,
				RRGPMas.TransName,
				RRGPMas.TransDocDate,
				RRGPMas.VehicleNo,
				Case when RRGPmas.TransMode = 1 then 'By Road' when 
				RRGPmas.TransMode = 2 then 'By Train' When 
				RRGPmas.TransMode = 3 then 'By Air' When 
				RRGPmas.TransMode = 4 then 'by Ship' End as TransportMode,
				RRGPMas.TotalQty,
				RRGPMas.TaxableAmt as TaxableAmount,
				RRGPMas.TaxPerc1,
				RRGPMas.TaxPerc2,
				RRGPMas.GstAmt1,
				RRGPMas.GstAmt2,
				RRGPMas.OtherAmt,
				RRGPMas.TotalAmt,
				dbo.NumberToWords(RRGPMas.TotalAmt) AS AmountInWords,
                JobWorkProcessMas.JobWorkProcessName as PurposName,
                RGPmas.ewayBillNo,
				RGPmas.ewayBillDate,
				RGPmas.LocationCode,
				RGPmas.EwbValidTill,
                RRGPMas.Disp_fromAddr1,
				RRGPMas.Disp_fromAddr2,
				RRGPMas.Disp_fromPlace,
				RRGPMas.Disp_fromPincode,
				RRGPMas.Disp_actFromStateCode,
                StateMas3.StateName as StateName3,
				CASE WHEN RRGPMas.TransType=1 THEN 'REGULAR'
				WHEN RRGPMas.TransType=2 THEN 'BILL TO SHIP TO'
				WHEN RRGPMas.TransType=3 THEN 'BILL FROM-DISPATCH FROM'
				WHEN RRGPMas.TransType=4 THEN '--' END AS Ewb_TransType";
            public const string RRGPDet = $@"CAST(ROW_NUMBER() OVER (ORDER BY  RawMas.Rawdesc) AS INT) AS DETAIL_SrNo, RRGPDet.qty as DETAIL_QTY,
                RRGPDet.Rate as DETAIL_RRGPRate, RRGPDet.Amount as DETAIL_Amount, 
                RRGPDet.Opfield1 as DETAIL_Optional1,
				RRGPDet.Opfield2 as DETAIL_Optional2,
				RRGPDet.Opfield3 as DETAIL_Optional3,
				RRGPDet.Opfield4 as DETAIL_Optional4,
				RRGPDet.Opfield5 as DETAIL_Optional5,
				RRGPDet.Opfield6 as DETAIL_Optional6,
				RRGPDet.Opfield7 as DETAIL_Optional7,
				RRGPDet.Opfield8 as DETAIL_Optional8,
				RRGPDet.Opfield9 as DETAIL_Optional9,
				RRGPDet.Opfield10 as DETAIL_Optional10,
				RRGPDet.TaxableAmount as DETAIL_TaxableAmount,
				RRGPDet.GST1 as DETAIL_GST1,
				RRGPDet.GST2 as DETAIL_GST2,
				RRGPDet.GST1Amt as DETAIL_GST1Amt,
				RRGPDet.GST2Amt as DETAIL_GST2Amt,
				RRGPDet.TotalAmount as DETAIL_TotalAmount,
				RRGPDet.GST1+RRGPDet.GST2 as DETAIL_TOT_GST,
				RRGPDet.GST1Amt+RRGPDet.GST2Amt as DETAIL_TOT_GSTAmt";

            public const string MRNDet = $@"MRNDet.Srno DETAIL_Srno,
                                            MRNDet.ChallanQty DETAIL_ChallanQty,
                                            MRNDet.RecQty DETAIL_RecQty,
                                            MRNDet.AcceptQty DETAIL_AcceptQty,
                                            MRNDet.PendingQty DETAIL_PendingQty,
                                            MRNDet.Rate DETAIL_Rate,
                                            MRNDet.Amount DETAIL_Amount,
                                            MRNDet.Opfield1 DETAIL_Opfield1,
                                            MRNDet.Opfield2 DETAIL_Opfield2,
                                            MRNDet.Opfield3 DETAIL_Opfield3,
                                            MRNDet.Opfield4 DETAIL_Opfield4,
                                            MRNDet.Opfield5 DETAIL_Opfield5,
                                            MRNDet.Opfield6 DETAIL_Opfield6,
                                            MRNDet.Opfield7 DETAIL_Opfield7,
                                            MRNDet.Opfield8 DETAIL_Opfield8,
                                            MRNDet.Opfield9 DETAIL_Opfield9,
                                            MRNDet.Opfield10 DETAIL_Opfield10,
                                            MRNDet.QcDone DETAIL_QcDone";
            public const string MRNMas = $@"MRNMas.MrnCode as MRN_Code ,
                                            MRNMas.MrnDate as  MRN_Date,
                                            MRNMas.MrnDocNo as  MRN_DocNo,
                                            MRNMas.SeriesCode as  MRN_SeriesCode,
                                            MRNMas.AccCode as  MRN_AccCode,
                                            MRNMas.ChNo as  MRN_ChNo,
                                            MRNMas.ChDate as  MRN_ChDate,
                                            MRNMas.BillNo as  MRN_BillNo,
                                            MRNMas.BillDate as  MRN_BillDate,
                                            MRNMas.Remarks ,
                                            MRNMas.YearCode as  MRN_YearCode,
                                            MRNMas.OrderNo as  MRN_OrderNo,
                                            MRNMas.Approval ,
                                            MRNMas.MRNAmt as  MRN_Amt,
                                            MRNMas.OtherCharges,
                                            MRNMas.TaxableAmt as  Taxable_Amt,
                                            MRNMas.Tax1Perc as  Tax1_Perc,
                                            MRNMas.Tax1Amt as  Tax1_Amt,
                                            MRNMas.Tax2Perc as  Tax2_Perc,
                                            MRNMas.Tax2Amt as  Tax2_Amt,
                                            MRNMas.VechileNo as  Vechile_No,
                                            MRNMas.Narr1 as  Narration1,
                                            MRNMas.Narr2 as  Narration2,
                                            MRNMas.Narr3 as  Narration3,
                                            MRNMas.Narr4 as  Narration4,
                                            MRNMas.Narr5 as  Narration5,
                                            MRNMas.Narr6 as  Narration6,
                                            MRNMas.Narr7 as  Narration7,
                                            MRNMas.Narr8 as  Narration8,
                                            MRNMas.Narr9 as  Narration9,
                                            MRNMas.Narr10 as  Narration10";
            public const string JobWorkMas = $@"JobWorkMas.JobWorkCode as JobWork_Code,
                                            JobWorkMas.JobWorkDate as JobWork_Date,
                                            JobWorkMas.JobWorkDocNo as JobWork_DocNo,
                                            JobWorkMas.Remarks,
                                            JobWorkMas.saleblno,
                                            JobWorkMas.blno,
                                            JobWorkMas.OtherAmt1,
                                            JobWorkMas.OtherAmt2,
                                            JobWorkMas.OtherAmt3,
                                            JobWorkMas.OtherAmt4,
                                            JobWorkMas.OtherAmt5,
                                            JobWorkMas.OtherCap1,
                                            JobWorkMas.OtherCap2,
                                            JobWorkMas.OtherCap3,
                                            JobWorkMas.OtherCap4,
                                            JobWorkMas.OtherCap5,
                                            JobWorkMas.JobWorkAmt as JobWorkAmt_Amt,
                                            JobWorkMas.Narr1 as Narration1,
                                            JobWorkMas.Narr2 as Narration2,
                                            JobWorkMas.Narr3 as Narration3,
                                            JobWorkMas.Narr4 as Narration4,
                                            JobWorkMas.Narr5 as Narration5,
                                            JobWorkMas.Narr6 as Narration6,
                                            JobWorkMas.Narr7 as Narration7,
                                            JobWorkMas.Narr8 as Narration8,
                                            JobWorkMas.Narr9 as Narration9,
                                            JobWorkMas.Narr10 as Narration10,
                                            JobWorkMas.DeliveryDate as Delivery_Date,
                                            JobWorkMas.IsCancel,
                                            JobWorkMas.CashReceived1 as Cash_Received1,
                                            JobWorkMas.CashReceived2 as Cash_Received2,
                                            JobWorkMas.CashReceived3 as Cash_Received3,
                                            JobWorkMas.CashReceived4 as Cash_Received4,
                                            JobWorkMas.CashReceived5 as Cash_Received5,
                                            JobWorkMas.ReceiveDate1,
                                            JobWorkMas.ReceiveDate2,
                                            JobWorkMas.ReceiveDate3,
                                            JobWorkMas.ReceiveDate4,
                                            JobWorkMas.ReceiveDate5,
                                            JobWorkMas.IsDelivery,
                                            JobWorkMas.UserCodeReceive1,
                                            JobWorkMas.UserCodeReceive2,
                                            JobWorkMas.ContactPerson as Contact_Person,
                                            JobWorkMas.Pay1,
                                            JobWorkMas.Pay2,
                                            JobWorkMas.Pay3,
                                            JobWorkMas.Pay4,
                                            JobWorkMas.Pay5,
                                            JobWorkMas.PONo";
            public const string JobWorkDet = $@"JobWorkDet.Srno as DETAIL_Srno,
                                            JobWorkDet.Qty as DETAIL_Qty,
                                            JobWorkDet.Rate as DETAIL_Rate,
                                            JobWorkDet.Amount as DETAIL_Amount,
                                            JobWorkDet.ToBill as DETAIL_ToBill,
                                            JobWorkDet.MachineCode as DETAIL_MachineCode,
                                            JobWorkDet.ColourCode as DETAIL_ColourCode,
                                            JobWorkDet.Height as DETAIL_Height,
                                            JobWorkDet.Width as DETAIL_Width,
                                            JobWorkDet.Opfield1 as DETAIL_Opfield1,
                                            JobWorkDet.Opfield2 as DETAIL_Opfield2,
                                            JobWorkDet.Opfield3 as DETAIL_Opfield3,
                                            JobWorkDet.Opfield4 as DETAIL_Opfield4,
                                            JobWorkDet.Opfield5 as DETAIL_Opfield5,
                                            JobWorkDet.Opfield6 as DETAIL_Opfield6,
                                            JobWorkDet.Opfield7 as DETAIL_Opfield7,
                                            JobWorkDet.Opfield8 as DETAIL_Opfield8,
                                            JobWorkDet.Opfield9 as DETAIL_Opfield9,
                                            JobWorkDet.Opfield10 as DETAIL_Opfield10";
            public const string JobWorkPrintMas = $@"JobWorkPrintMas.JobWorkCode as JobWork_Code,
                                            JobWorkPrintMas.JobWorkDate as JobWork_Date,
                                            JobWorkPrintMas.JobWorkDocNo as JobWork_DocNo,
                                            JobWorkPrintMas.Remarks,
                                            JobWorkPrintMas.saleblno,
                                            JobWorkPrintMas.blno,
                                            JobWorkPrintMas.OtherAmt1,
                                            JobWorkPrintMas.OtherAmt2,
                                            JobWorkPrintMas.OtherAmt3,
                                            JobWorkPrintMas.OtherAmt4,
                                            JobWorkPrintMas.OtherAmt5,
                                            JobWorkPrintMas.OtherCap1,
                                            JobWorkPrintMas.OtherCap2,
                                            JobWorkPrintMas.OtherCap3,
                                            JobWorkPrintMas.OtherCap4,
                                            JobWorkPrintMas.OtherCap5,
                                            JobWorkPrintMas.JobWorkAmt as JobWorkAmt_Amt,
                                            JobWorkPrintMas.Narr1 as Narration1,
                                            JobWorkPrintMas.Narr2 as Narration2,
                                            JobWorkPrintMas.Narr3 as Narration3,
                                            JobWorkPrintMas.Narr4 as Narration4,
                                            JobWorkPrintMas.Narr5 as Narration5,
                                            JobWorkPrintMas.Narr6 as Narration6,
                                            JobWorkPrintMas.Narr7 as Narration7,
                                            JobWorkPrintMas.Narr8 as Narration8,
                                            JobWorkPrintMas.Narr9 as Narration9,
                                            JobWorkPrintMas.Narr10 as Narration10,
                                            JobWorkPrintMas.DeliveryDate as Delivery_Date,
                                            JobWorkPrintMas.IsCancel,
                                            JobWorkPrintMas.CashReceived1 as Cash_Received1,
                                            JobWorkPrintMas.CashReceived2 as Cash_Received2,
                                            JobWorkPrintMas.CashReceived3 as Cash_Received3,
                                            JobWorkPrintMas.CashReceived4 as Cash_Received4,
                                            JobWorkPrintMas.CashReceived5 as Cash_Received5,
                                            JobWorkPrintMas.ReceiveDate1,
                                            JobWorkPrintMas.ReceiveDate2,
                                            JobWorkPrintMas.ReceiveDate3,
                                            JobWorkPrintMas.ReceiveDate4,
                                            JobWorkPrintMas.ReceiveDate5,
                                            JobWorkPrintMas.IsDelivery,
                                            JobWorkPrintMas.UserCodeReceive1,
                                            JobWorkPrintMas.UserCodeReceive2,
                                            JobWorkPrintMas.ContactPerson as Contact_Person,
                                            JobWorkPrintMas.Pay1,
                                            JobWorkPrintMas.Pay2,
                                            JobWorkPrintMas.Pay3,
                                            JobWorkPrintMas.Pay4,
                                            JobWorkPrintMas.Pay5,
                                            JobWorkPrintMas.PONo";

            public const string JobWorkPrintDet = $@"JobWorkPrintDet.Srno as DETAIL_Srno,
                                            JobWorkPrintDet.Qty as DETAIL_Qty,
                                            JobWorkPrintDet.Rate as DETAIL_Rate,
                                            JobWorkPrintDet.Amount as DETAIL_Amount,
                                            JobWorkPrintDet.ToBill as DETAIL_ToBill,
                                            JobWorkPrintDet.MachineCode as DETAIL_MachineCode,
                                            JobWorkPrintDet.ColourCode as DETAIL_ColourCode,
                                            JobWorkPrintDet.Height as DETAIL_Height,
                                            JobWorkPrintDet.Width as DETAIL_Width,
                                            JobWorkPrintDet.Opfield1 as DETAIL_Opfield1,
                                            JobWorkPrintDet.Opfield2 as DETAIL_Opfield2,
                                            JobWorkPrintDet.Opfield3 as DETAIL_Opfield3,
                                            JobWorkPrintDet.Opfield4 as DETAIL_Opfield4,
                                            JobWorkPrintDet.Opfield5 as DETAIL_Opfield5,
                                            JobWorkPrintDet.Opfield6 as DETAIL_Opfield6,
                                            JobWorkPrintDet.Opfield7 as DETAIL_Opfield7,
                                            JobWorkPrintDet.Opfield8 as DETAIL_Opfield8,
                                            JobWorkPrintDet.Opfield9 as DETAIL_Opfield9,
                                            JobWorkPrintDet.Opfield10 as DETAIL_Opfield10";

            public const string IndentMas = $@"IndentMas.IndentCode as Indent_Code,
                                            IndentMas.IndentDocNo as Indent_DocNo,
                                            IndentMas.IndentDate as Indent_Date,
                                            IndentMas.BuyerRefNo,
                                            IndentMas.Approval,
                                            IndentMas.Remarks,
                                            IndentMas.Narr1 as Narration1,
                                            IndentMas.Narr2 as Narration2,
                                            IndentMas.Narr3 as Narration3,
                                            IndentMas.Narr4 as Narration4,
                                            IndentMas.Narr5 as Narration5,
                                            IndentMas.Narr6 as Narration6,
                                            IndentMas.Narr7 as Narration7,
                                            IndentMas.Narr8 as Narration8,
                                            IndentMas.Narr9 as Narration9,
                                            IndentMas.Narr10 as Narration10";
            public const string IndentDet = $@"IndentDet.SrNO as DETAIL_SrNO,
                                            IndentDet.QtyIndent as DETAIL_QtyIndent,
                                            IndentDet.QtyApprove as DETAIL_QtyApprove,
                                            IndentDet.TargetDate as DETAIL_TargetDate,
                                            IndentDet.Opfield_1 as DETAIL_Opfield_1,
                                            IndentDet.Opfield_2 as DETAIL_Opfield_2,
                                            IndentDet.Opfield_3 as DETAIL_Opfield_3,
                                            IndentDet.Opfield_4 as DETAIL_Opfield_4,
                                            IndentDet.Opfield_5 as DETAIL_Opfield_5,
                                            IndentDet.Opfield_6 as DETAIL_Opfield_6,
                                            IndentDet.Opfield_7 as DETAIL_Opfield_7,
                                            IndentDet.Opfield_8 as DETAIL_Opfield_8,
                                            IndentDet.Opfield_9 as DETAIL_Opfield_9,
                                            IndentDet.Opfield_10 as DETAIL_Opfield_10";

            public const string QuoteMas = $@"QuoteMas.QuoteDocNo as Quote_DocNo,
                                            QuoteMas.QuoteDate as Quote_Date,
                                            QuoteMas.BuyerRefNo,
                                            QuoteMas.Approval,
                                            QuoteMas.Remarks,
                                            QuoteMas.Narr1 as Narration1,
                                            QuoteMas.Narr2 as Narration2,
                                            QuoteMas.Narr3 as Narration3,
                                            QuoteMas.Narr4 as Narration4,
                                            QuoteMas.Narr5 as Narration5,
                                            QuoteMas.Narr6 as Narration6,
                                            QuoteMas.Narr7 as Narration7,
                                            QuoteMas.Narr8 as Narration8,
                                            QuoteMas.Narr9 as Narration9,
                                            QuoteMas.Narr10 as Narration10,
                                            QuoteMas.QuoteAmt as Quote_Amt";

            public const string QuoteDet = $@"QuoteDet.SrNO as DETAIL_SrNO,
                                            QuoteDet.Qty as DETAIL_Qty,
                                            QuoteDet.Rate as DETAIL_Rate,
                                            QuoteDet.Amount as DETAIL_Amount,
                                            QuoteDet.Opfield_1 as DETAIL_Opfield_1,
                                            QuoteDet.Opfield_2 as DETAIL_Opfield_2,
                                            QuoteDet.Opfield_3 as DETAIL_Opfield_3,
                                            QuoteDet.Opfield_4 as DETAIL_Opfield_4,
                                            QuoteDet.Opfield_5 as DETAIL_Opfield_5,
                                            QuoteDet.Opfield_6 as DETAIL_Opfield_6,
                                            QuoteDet.Opfield_7 as DETAIL_Opfield_7,
                                            QuoteDet.Opfield_8 as DETAIL_Opfield_8,
                                            QuoteDet.Opfield_9 as DETAIL_Opfield_9,
                                            QuoteDet.Opfield_10 as DETAIL_Opfield_10";

            public const string PurchaseReturnMas = $@"PurchaseReturnMas.PurchaseReturnDate as PurchaseReturn_Date,
                                            PurchaseReturnMas.DocNo as PurchaseReturn_DocNo,
                                            PurchaseReturnMas.chno as ChallanNo,
                                            PurchaseReturnMas.chdate as ChallanDate ,
                                            PurchaseReturnMas.BillAmt as PurchaseReturn_AMOUNT,
                                            PurchaseReturnMas.TaxableAmt as PurchaseReturn_TaxableAmt,
                                            PurchaseReturnMas.GST1 as GST_1,
                                            PurchaseReturnMas.GST1Amt as GST1_Amt,
                                            PurchaseReturnMas.GST2 as GST_2,
                                            PurchaseReturnMas.GST2Amt as GST2_Amt,
                                            PurchaseReturnMas.COther1,
                                            PurchaseReturnMas.COther2,
                                            PurchaseReturnMas.COther3,
                                            PurchaseReturnMas.COther4,
                                            PurchaseReturnMas.COther5,
                                            PurchaseReturnMas.COther6,
                                            PurchaseReturnMas.OtherAmt1,
                                            PurchaseReturnMas.OtherAmt2,
                                            PurchaseReturnMas.OtherAmt3,
                                            PurchaseReturnMas.OtherAmt4,
                                            PurchaseReturnMas.OtherAmt5,
                                            PurchaseReturnMas.OtherAmt6,
                                            PurchaseReturnMas.Perc1,
                                            PurchaseReturnMas.Perc2,
                                            PurchaseReturnMas.Perc3,
                                            PurchaseReturnMas.Perc4,
                                            PurchaseReturnMas.Perc5,
                                            PurchaseReturnMas.Narr1 as Narration1,
                                            PurchaseReturnMas.Narr2 as Narration2,
                                            PurchaseReturnMas.Narr3 as Narration3,
                                            PurchaseReturnMas.Narr4 as Narration4,
                                            PurchaseReturnMas.Narr5 as Narration5,
                                            PurchaseReturnMas.Narr6 as Narration6,
                                            PurchaseReturnMas.Narr7 as Narration7,
                                            PurchaseReturnMas.Narr8 as Narration8,
                                            PurchaseReturnMas.Narr9 as Narration9,
                                            PurchaseReturnMas.Narr10 as Narration10,
                                            PurchaseReturnMas.Narr11 as Narration11,
                                            PurchaseReturnMas.Narr12 as Narration12,
                                            PurchaseReturnMas.Narr13 as Narration13,
                                            PurchaseReturnMas.Narr14 as Narration14,
                                            PurchaseReturnMas.Narr15 as Narration15,
                                            PurchaseReturnMas.Narr16 as Narration16,
                                            PurchaseReturnMas.Narr17 as Narration17,
                                            PurchaseReturnMas.Narr18 as Narration18,
                                            PurchaseReturnMas.Narr19 as Narration19,
                                            PurchaseReturnMas.PurchaseReturnNarration as PurchaseReturn_Narration,
                                            PurchaseReturnMas.TotalAmt as PurchaseReturn_TotalAmt";
            public const string PurchaseReturnDet = $@"PurchaseReturnDet.SrNo as DETAIL_SrNo,
                                            PurchaseReturnDet.Pack as DETAIL_Pack,
                                            PurchaseReturnDet.PerPackQty as DETAIL_PerPackQty,
                                            PurchaseReturnDet.qty as DETAIL_qty,
                                            PurchaseReturnDet.GST1 as DETAIL_GST1,
                                            PurchaseReturnDet.GST1Amt as DETAIL_GST1Amt,
                                            PurchaseReturnDet.GST2 as DETAIL_GST2,
                                            PurchaseReturnDet.GST2Amt as DETAIL_GST2Amt,
                                            PurchaseReturnDet.Amount as DETAIL_Amount,
                                            PurchaseReturnDet.ItRate as DETAIL_ItRate,
                                            PurchaseReturnDet.ItMrp as DETAIL_ItMrp,
                                            PurchaseReturnDet.Disc as DETAIL_Disc,
                                            PurchaseReturnDet.DiscAmt as DETAIL_DiscAmt,
                                            PurchaseReturnDet.ChallanCode as DETAIL_ChallanCode,
                                            PurchaseReturnDet.ChallanSrNo as DETAIL_ChallanSrNo,
                                            PurchaseReturnDet.Opfield1 as DETAIL_Opfield1,
                                            PurchaseReturnDet.Opfield2 as DETAIL_Opfield2,
                                            PurchaseReturnDet.Opfield3 as DETAIL_Opfield3,
                                            PurchaseReturnDet.Opfield4 as DETAIL_Opfield4,
                                            PurchaseReturnDet.Opfield5 as DETAIL_Opfield5,
                                            PurchaseReturnDet.Opfield6 as DETAIL_Opfield6,
                                            PurchaseReturnDet.Opfield7 as DETAIL_Opfield7,
                                            PurchaseReturnDet.Opfield8 as DETAIL_Opfield8,
                                            PurchaseReturnDet.Opfield9 as DETAIL_Opfield9,
                                            PurchaseReturnDet.Opfield10 as DETAIL_Opfield10,
                                            PurchaseReturnDet.OrderNo as DETAIL_OrderNo,
                                            PurchaseReturnDet.Orderdate as DETAIL_Orderdate";

            public const string SaleReturnMas = $@"SaleReturnMas.SaleReturnNo as SaleReturn_No,
                                            SaleReturnMas.SaleReturnDate as SaleReturn_Date,
                                            SaleReturnMas.ChallanNo,
                                            SaleReturnMas.ChallanNoDate,
                                            SaleReturnMas.BillAmt,
                                            SaleReturnMas.TaxableAmt as SaleReturn_TaxableAmt,
                                            SaleReturnMas.GST1Perc as GST1_Perc,
                                            SaleReturnMas.GST1Amt as GST1_Amt,
                                            SaleReturnMas.GST2 as GST2,
                                            SaleReturnMas.GST2Amt as GST2_Amt,
                                            SaleReturnMas.ordno,
                                            SaleReturnMas.orddate,
                                            SaleReturnMas.narr as Narration,
                                            SaleReturnMas.COther1,
                                            SaleReturnMas.COther2,
                                            SaleReturnMas.COther3,
                                            SaleReturnMas.COther4,
                                            SaleReturnMas.COther5,
                                            SaleReturnMas.Other1,
                                            SaleReturnMas.Other2,
                                            SaleReturnMas.Other3,
                                            SaleReturnMas.Other4,
                                            SaleReturnMas.Other5,
                                            SaleReturnMas.Narr1 as Narration1,
                                            SaleReturnMas.Narr2 as Narration2,
                                            SaleReturnMas.Narr3 as Narration3,
                                            SaleReturnMas.Narr4 as Narration4,
                                            SaleReturnMas.Narr5 as Narration5,
                                            SaleReturnMas.Narr6 as Narration6,
                                            SaleReturnMas.Narr7 as Narration7,
                                            SaleReturnMas.Narr8 as Narration8,
                                            SaleReturnMas.Narr9 as Narration9,
                                            SaleReturnMas.Narr10 as Narration10";
            public const string SaleReturnDet = $@"SaleReturnDet.MrnCode as DETAIL_MrnCode,
                                            SaleReturnDet.POCode as DETAIL_POCode,
                                            SaleReturnDet.SrNo as DETAIL_SrNo,
                                            SaleReturnDet.Qty as DETAIL_Qty,
                                            SaleReturnDet.GST1Perc as DETAIL_GST1Perc,
                                            SaleReturnDet.GST1Amt as DETAIL_GST1Amt,
                                            SaleReturnDet.GST2Perc as DETAIL_GST2Perc,
                                            SaleReturnDet.GST2Amt as DETAIL_GST2Amt,
                                            SaleReturnDet.CessPerc as DETAIL_CessPerc,
                                            SaleReturnDet.CessAmt as DETAIL_CessAmt,
                                            SaleReturnDet.SaleRate as DETAIL_SaleRate,
                                            SaleReturnDet.Amount as DETAIL_Amount,
                                            SaleReturnDet.HSNCode as DETAIL_HSNCode,
                                            SaleReturnDet.MRP as DETAIL_MRP";

            public const string POMas = $@"POMas.PODocNo as PO_DocNo,
                                            POMas.PODate as PO_Date,
                                            POMas.RefNo as Ref_No,
                                            POMas.RefDate as Ref_Date,
                                            POMas.IndentCode as Indent_Code,
                                            POMas.ValidFrom as Valid_From,
                                            POMas.ValidTo as Valid_To,
                                            POMas.Narr1 as Narration1,
                                            POMas.Narr2 as Narration2,
                                            POMas.Narr3 as Narration3,
                                            POMas.Narr4 as Narration4,
                                            POMas.Narr5 as Narration5,
                                            POMas.Narr6 as Narration6,
                                            POMas.Narr7 as Narration7,
                                            POMas.Narr8 as Narration8,
                                            POMas.Narr9 as Narration9,
                                            POMas.Narr10 as Narration10,
                                            POMas.Narr11 as Narration11,
                                            POMas.Narr12 as Narration12,
                                            POMas.Narr13 as Narration13,
                                            POMas.Narr14 as Narration14,
                                            POMas.Narr15 as Narration15,
                                            POMas.Narr16 as Narration16,
                                            POMas.Narr17 as Narration17,
                                            POMas.Narr18 as Narration18,
                                            POMas.Narr19 as Narration19,
                                            POMas.Narr20 as Narration20,
                                            POMas.SalePurcType as SalePurcType,
                                            POMas.TaxableAmt as PO_TaxableAmt,
                                            POMas.Tax1 as Tax_1,
                                            POMas.Tax1Amt as Tax1_Amt,
                                            POMas.Tax2 as Tax_2,
                                            POMas.Tax2Amt as Tax2_Amt,
                                            POMas.POAmt as PO_AMOUNT";
            public const string PODet = $@"PODet.SrNo as DETAIL_SrNo,
                                            PODet.Qty as DETAIL_Qty,
                                            PODet.Rate as DETAIL_Rate,
                                            PODet.Amount as DETAIL_Amount,
                                            PODet.DiscPerc as DETAIL_DiscPerc,
                                            PODet.DiscAmt as DETAIL_DiscAmt,
                                            PODet.GST1Perc as DETAIL_GST1Perc,
                                            PODet.GST1Amt as DETAIL_GST1Amt,
                                            PODet.GST2Perc as DETAIL_GST2Perc,
                                            PODet.GST2Amt as DETAIL_GST2Amt,
                                            PODet.ItemAmt as DETAIL_ItemAmt,
                                            PODet.OpField1 as DETAIL_OpField1,
                                            PODet.OpField2 as DETAIL_OpField2,
                                            PODet.OpField3 as DETAIL_OpField3,
                                            PODet.OpField4 as DETAIL_OpField4,
                                            PODet.OpField5 as DETAIL_OpField5,
                                            PODet.OpField6 as DETAIL_OpField6,
                                            PODet.OpField7 as DETAIL_OpField7,
                                            PODet.OpField8 as DETAIL_OpField8,
                                            PODet.OpField9 as DETAIL_OpField9,
                                            PODet.OpField10 as DETAIL_OpField10";

            public const string SOMas = $@"SaleOrderMas.SaleOrderDate as SO_Date,
                                            SaleOrderMas.SaleOrderDocNo as SO_DocNo,
                                            SaleOrderMas.IsFixQty as Is_Fix_Qty,
                                            SaleOrderMas.IsActive as Is_Active,
                                            SaleOrderMas.DeliveryDate as Delivery_Date,
                                            SaleOrderMas.Remarks,
                                            SaleOrderMas.OtherAmt1,
                                            SaleOrderMas.OtherAmt2,
                                            SaleOrderMas.OtherAmt3,
                                            SaleOrderMas.OtherAmt4,
                                            SaleOrderMas.OtherAmt5,
                                            SaleOrderMas.TaxableAmt as Taxable_Amt,
                                            SaleOrderMas.SaleOrderAmt as SO_Amt,
                                            SaleOrderMas.COther1,
                                            SaleOrderMas.COther2,
                                            SaleOrderMas.COther3,
                                            SaleOrderMas.COther4,
                                            SaleOrderMas.COther5,
                                            SaleOrderMas.OtherPerc1,
                                            SaleOrderMas.OtherPerc2,
                                            SaleOrderMas.OtherPerc3,
                                            SaleOrderMas.OtherPerc4,
                                            SaleOrderMas.OtherPerc5,
                                            SaleOrderMas.Narr1 as Narration1,
                                            SaleOrderMas.Narr2 as Narration2,
                                            SaleOrderMas.Narr3 as Narration3,
                                            SaleOrderMas.Narr4 as Narration4,
                                            SaleOrderMas.Narr5 as Narration5,
                                            SaleOrderMas.Narr6 as Narration6,
                                            SaleOrderMas.Narr7 as Narration7,
                                            SaleOrderMas.Narr8 as Narration8,
                                            SaleOrderMas.Narr9 as Narration9,
                                            SaleOrderMas.Narr10 as Narration10";
            public const string SODet = $@"SaleOrderDet.SrNO as DETAIL_SrNO,
                                            SaleOrderDet.Qty as DETAIL_Qty,
                                            SaleOrderDet.Rate as DETAIL_Rate,
                                            SaleOrderDet.Amount as DETAIL_Amount,
                                            SaleOrderDet.Tolerance as DETAIL_Tolerance,
                                            SaleOrderDet.IsHold as DETAIL_IsHold,
                                            SaleOrderDet.DeliveryDateDetail as DETAIL_DeliveryDateDetail";
        }
    }
}
